spring.application.name=security
spring.datasource.url= jdbc:postgresql://localhost:5432/security
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=shiva
spring.security.user.password=shiva@123
